#!/bin/bash

set -e

read -p "Enter GCS bucket: " bucket

mkdir -p ../input
if [ ! -e "../input/UK-dem-50m-4326.tif" ]; then
	# Generated by Malcolm Morgan using
	# https://github.com/mem48/OTPR/blob/master/scripts/prep_DEM.R. The
	# input data is
	# https://www.ordnancesurvey.co.uk/products/os-terrain-50.
	wget https://play.abstreet.org/dev/data/input/shared/elevation/UK-dem-50m-4326.tif.gz -P ../input
	gunzip ../input/UK-dem-50m-4326.tif.gz
fi

for country in "england" "wales" "scotland"; do
	if [ ! -e "../input/${country}-240901.osm.pbf" ]; then
		wget https://download.geofabrik.de/europe/united-kingdom/${country}-240901.osm.pbf -O ../input/${country}-240901.osm.pbf
	fi
done

if [ ! -e "../input/pt_route_timetables_2022.json" ]; then
	gsutil -m cp gs://${bucket}/pt_preprocessing/pt_route_timetables_2022.json ../input/pt_route_timetables_2022.json
fi

if [ ! -e "../input/pt_stop_coordinates_2022.json" ]; then
	gsutil -m cp gs://${bucket}/pt_preprocessing/pt_stop_coordinates_2022.json ../input/pt_stop_coordinates_2022.json
fi

mkdir -p ../data
# Assume the root directory has the osm.pbf, used by many other scripts in this repo
time cargo run --release \
	../input/england-240901.osm.pbf \
	../input/wales-240901.osm.pbf \
	../input/scotland-240901.osm.pbf \
	../input/UK-dem-50m-4326.tif \
	../data \
	true \
	../input/pt_route_timetables_2022.json \
	../input/pt_stop_coordinates_2022.json
