#!/bin/bash

set -e

mkdir -p ../input
if [ ! -e "../input/UK-dem-50m-4326.tif" ]; then
	# Generated by Malcolm Morgan using
	# https://github.com/mem48/OTPR/blob/master/scripts/prep_DEM.R. The
	# input data is
	# https://www.ordnancesurvey.co.uk/products/os-terrain-50.
	wget https://play.abstreet.org/dev/data/input/shared/elevation/UK-dem-50m-4326.tif.gz -P ../input
	gunzip ../input/UK-dem-50m-4326.tif.gz
fi

if [ ! -e "../input/kent-240708.osm.pbf" ]; then
	wget http://download.geofabrik.de/europe/great-britain/england/kent-240708.osm.pbf -P ../input
fi

mkdir -p ../data
# Assume the root directory has the osm.pbf, used by many other scripts in this repo
time cargo run --release ../input/kent-240708.osm.pbf ../input/UK-dem-50m-4326.tif ../data
